version: '3'

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: tom
      MYSQL_DATABASE: test
      MYSQL_USER: tom
      MYSQL_PASSWORD: tom
    ports:
      - "3306:3306"
    networks:
      - coursenet
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin", "ping", "-h", "localhost"]

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/test_schema
      SPRING_DATASOURCE_USERNAME: tom
      SPRING_DATASOURCE_PASSWORD: tom
    restart: on-failure
    networks:
      - coursenet

  networks:
  coursenet:
    driver: bridge